
platform :ios, '7.0'

target 'SuperOX' do

pod 'Mantle'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'MagicalRecord'
pod 'SDAutoLayout'
pod 'HyphenateFullSDK'
pod 'ReactiveCocoa'

end